name: Build EasyOCR Docker Image

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - master
    paths:
      - 'Dockerfile.easyocr-test'
      - '.github/workflows/build-easyocr-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.easyocr-test
          push: true
          tags: donaldbraman/easyocr-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
